WIP: Migrate upload feature to nodejs #1127
linagora/Twake pull request #1139
Opened 2021-04-12 09:43 UTC by tissarni

Description todo

- [ ]  Create microservice for "files" [S1]
- [ ] Study Resumable.js alternative (that we'll call Resumable Upload Library later on) [S1]
- [ ]  Implement a simple POST that allows files to be uploaded [S2]
- [ ] Implement Resumable Upload Library (with custom simple html file for frontend) [S2]
- [ ]  Implement an adapter architecture for object storage ("S3" and "Swift" and "local") [S3]
- [ ] Add route to download chunked files [S4]

-> At this time we have chunk upload ready

- [ ] Encrypt upload stream [S5]
- [ ] Update download endpoint [S5]

-> At this time we have chunk encryption ready

Miscellaneous:

- [ ] Generate metadata
- [ ] Ability to download list of files ids in zip
- [ ]  Generate previews

2021-04-12 09:58 UTC, chamerling commented on twake/backend/node/src/core/platform/framework/api/service.ts
> +let pendingServices: any = {};
Looks like this is a `Map<string, boolean>`

2021-04-12 09:58 UTC, chamerling commented on twake/backend/node/src/services/files/entities/file.ts
> +  height: number;
These are parameters which will be used for images only, right? What about putting them in a JSON metadata field?

2021-04-12 09:58 UTC, chamerling commented on twake/backend/node/src/services/files/services/engine/index.ts
> +import { Initializable } from "../../../../core/platform/framework";
USeless file, looks like a copy/paste

2021-04-12 09:58 UTC, chamerling commented on twake/backend/node/src/services/files/web/controllers/files.ts
> +    data.mimetype;
USeless fields, but you can use a logger to log these details

2021-04-12 09:58 UTC, chamerling commented on twake/backend/node/src/services/files/web/controllers/files.ts
> +    await pump(data.file, fs.createWriteStream(data.filename));
If I am not wrong, you are streaming the file to nowhere.
From the documentation (https://nodejs.org/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback):

```
The pipeline API provides a promise version, which can also receive an options argument as the last parameter with a signal <AbortSignal> property. When the signal is aborted, destroy will be called on the underlying pipeline, with an AbortError.
```

Using the `AbortController ` will also be nice to handle aborted uploads

2021-04-12 09:58 UTC, chamerling commented on twake/backend/node/src/services/files/web/routes.ts
> +    url: `${filesUrl}/:upload`,
Can you give details about the `:upload` parameter?

2021-04-27 13:32 UTC, RomaricMourgues requested changes

2021-04-27 13:32 UTC, RomaricMourgues commented on twake/backend/node/config/default.json
> +    }
There should be default values here.
- For S3 you can put what you currently have without the api id and secret (replace it by admin/admin)
- For local you can put one folder:
   {
      "path": "/drive/"
   }

2021-04-27 13:32 UTC, RomaricMourgues commented on twake/backend/node/src/core/platform/services/storage/index.ts
> +
There will be other methods to implement:
- exists(path: string): Promise<boolean>
- remove(path: string): Promise<boolean>

2021-04-27 13:32 UTC, RomaricMourgues commented on twake/backend/node/src/core/platform/services/storage/index.ts
> +  }
It seems write and read should return Promises and not directly Streams (the PR is probably not up to date)

2021-04-27 13:32 UTC, RomaricMourgues commented on twake/backend/node/src/services/files/entities/file.ts
> +}
Must be updated with the latest documentation version (on notion)

2021-04-30 08:41 UTC, chamerling commented on twake/backend/node/package.json
> +    "@types/multistream": "^2.1.1",
Remove this one, we saw that it is not for the multistream version we use

2021-04-30 08:41 UTC, chamerling commented on twake/backend/node/src/core/platform/services/storage/connectors/S3/service.ts
>        `/twake/files/${company_id}/${user_id}/${folder_Name}/` + stream.data.filename,
```js
`/twake/files/${company_id}/${user_id}/${folder_Name}/${stream.data.filename}`
```

2021-04-30 08:41 UTC, chamerling commented on twake/backend/node/src/services/files/api.ts
>    save(stream: any): any;
You will need to define real type in this API, not `any`

2021-04-30 08:41 UTC, chamerling commented on twake/backend/node/src/services/files/api.ts
> +  download(path: any): Promise<Readable>;
`path: string`

2021-04-30 08:41 UTC, chamerling commented on twake/backend/node/src/services/files/web/controllers/files.ts
> +    response.send(new Multistream(factory));
Cool :)

2021-05-12 19:24 UTC, chamerling commented
I will try to take a look during holidays

2021-05-12 19:26 UTC, RomaricMourgues commented
I will do some additional changes next week and also merge documentation that waits here: https://github.com/linagora/Twake-Documentation/pull/3

2021-05-17 08:51 UTC, RomaricMourgues commented
> I will do some additional changes next week and also merge documentation that waits here: [linagora/Twake-Documentation#3](https://github.com/linagora/Twake-Documentation/pull/3)

Ok for me, it's ready

2021-05-25 13:42 UTC, chamerling requested changes
This is almost good! Great job

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/core/platform/services/storage/connectors/S3/service.ts
> +  write(path: string, stream: Readable) {
Even if `void` or `Promise<void>`, it will be nice to have the ouput type. Same for the local implementation

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/core/platform/services/storage/index.ts
> +  globalEncryption: { secret: string | null; iv: string | null } = { secret: null, iv: null };
should be `private`

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/core/platform/services/storage/index.ts
> +  globalEncryption: { secret: string | null; iv: string | null } = { secret: null, iv: null };
Wy it is called `global`? This is just `encryptionOptions` composed of a `key` and an `iv`

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/api.ts
> +  save(id: string, file: Multipart, options: UploadOptions, context: CompanyExecutionContext): any;
Can't we have something else than `any`?

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/services/index.ts
> +      console.error("Error while initializing notification service", err);
should be a `logger` call, not a console one

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/services/index.ts
> +        throw "This file id does not exist";
`throw new Error("The error message");`

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/services/index.ts
> +      this.repository.save(entity);
You should await for the save

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/services/index.ts
> +          this.repository.save(entity);
You should await for the save

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/services/index.ts
> +      var cipher = createCipheriv(
use `const`

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/services/index.ts
> +        entity.encryption_key.split(".")[1],
You split 2 times when you can do it once

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/services/index.ts
> +    var count = 1;
Use `let`

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/services/index.ts
> +        entity.encryption_key.split(".")[1],
split once

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/web/controllers/files.ts
> +      Querystring: any;
Please define the type

2021-05-25 13:42 UTC, chamerling commented on twake/backend/node/src/services/files/web/routes.ts
> +    preValidation: true ? [] : [fastify.authenticate],
Everyone can upload files then

2021-05-25 15:32 UTC, RomaricMourgues commented
As Titouan is not here anymore (back to school) I will take care of it when I find time, thanks @chamerling

2021-05-26 10:36 UTC, chamerling commented
I am on it @RomaricMourgues

2021-05-26 12:25 UTC, chamerling approved these changes

2021-05-26 12:31 UTC, merged