support increment type for cassandra and mongo
linagora/Twake pull request #1531
Opened 2021-08-04 14:23 UTC by romanesko

2021-08-05 07:30 UTC, chamerling requested changes

2021-08-05 07:30 UTC, chamerling commented on twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts
> +                column: { key: key },
```
column: { key }
```

is enough

2021-08-05 07:30 UTC, chamerling commented on twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/cassandra.ts
> +              column: { key: key },
Same here and below

2021-08-05 07:30 UTC, chamerling commented on twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/typeTransforms.ts
> +    if (isNaN(v)) throw Error("Counter value should be a number");
`throw new Error()`

2021-08-05 07:30 UTC, chamerling commented on twake/backend/node/src/core/platform/services/database/services/orm/connectors/cassandra/typeTransforms.ts
> +    return Number(v).valueOf();
is it better?

2021-08-05 07:30 UTC, chamerling commented on twake/backend/node/src/core/platform/services/database/services/orm/connectors/mongodb/typeTransforms.ts
> +    if (isNaN(v)) throw Error("Counter value should be a number");
new Error

2021-08-05 07:30 UTC, chamerling commented on twake/backend/node/test/e2e/counters.test.ts
> +  it("Initing empty value", async done => {
`Initializing empty value`

2021-08-06 07:14 UTC, RomaricMourgues approved these changes

2021-08-06 07:19 UTC, chamerling approved these changes

2021-08-06 07:34 UTC, merged