Async message + Fix (#580 #439 #1397 #699)
linagora/Twake pull request #1569
Opened 2021-08-19 16:22 UTC by BenoitTallandier

https://user-images.githubusercontent.com/22451567/130105959-ff038b8e-e5b1-4d5d-96af-aae0e209dfac.mov

https://user-images.githubusercontent.com/22451567/130105966-2a4bacae-2ea1-43de-993a-8e3e22af59cf.mov

2021-08-19 17:51 UTC, RomaricMourgues commented
Can we keep you in the dev team ? :p
That’s great !

> On 19 Aug 2021, at 18:22, Benoît Tallandier ***@***.***> wrote:
> 
> ﻿
>   slowNetwork.mov
> 
>   errorMessage.mov
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/linagora/Twake/pull/1569
> 
> Commit Summary
> 
> FIX #699
> FIX #1397
> Async message and retry #580 #439
> Fix design
> File Changes
> 
> M twake/frontend/public/locales/en.json (3475)
> M twake/frontend/public/locales/fr.json (3350)
> M twake/frontend/src/app/scenes/Apps/Messages/Input/Input.tsx (40)
> M twake/frontend/src/app/scenes/Apps/Messages/Message/Message.scss (77)
> M twake/frontend/src/app/scenes/Apps/Messages/Message/Message.tsx (2)
> M twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageContent.tsx (21)
> M twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageHeader.tsx (168)
> A twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/RetryButtons.tsx (34)
> M twake/frontend/src/app/scenes/Client/Popup/WorkspaceParameter/Pages/WorkspaceIdentity.js (2)
> M twake/frontend/src/app/services/Apps/Messages/MessageLoader.ts (18)
> M twake/frontend/src/app/services/Apps/Messages/Messages.tsx (44)
> M twake/frontend/src/app/services/Depreciated/Collections/Collection.js (12)
> M twake/frontend/src/app/services/login/AuthProviderService.ts (5)
> Patch Links:
> 
> https://github.com/linagora/Twake/pull/1569.patch
> https://github.com/linagora/Twake/pull/1569.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-20 07:53 UTC, chamerling commented
This is great 🎉

2021-08-20 07:57 UTC, chamerling commented on twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageContent.tsx
> +    (props.message as any)._failed || props.message.id == '6dec25e0-fc2e-11eb-a9c3-01401e397361';
what is it?

2021-08-20 07:57 UTC, chamerling commented on twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageHeader.tsx
> +          <AlertTriangle size={16} />
What happens then? DO we have a retry or edit button?

2021-08-20 07:57 UTC, chamerling commented on twake/frontend/src/app/services/Depreciated/Collections/Collection.js
> +            console.log('gga !!error!!');
ggaaaaaa!!!!!

2021-08-20 08:58 UTC, BenoitTallandier commented on twake/frontend/src/app/scenes/Apps/Messages/Message/Parts/MessageContent.tsx
> +    (props.message as any)._failed || props.message.id == '6dec25e0-fc2e-11eb-a9c3-01401e397361';
My bad, it's fixed ^^

2021-08-23 06:51 UTC, RomaricMourgues requested changes
You must solve the big changes on the languages files or it will break Weblate :)

2021-08-23 07:12 UTC, BenoitTallandier commented
> You must solve the big changes on the languages files or it will break Weblate :)

Are you sure ? I checked every locale file has 2 space as indentation. Only en and fr has 4. Do we want to keep this difference ? :)

2021-08-23 07:18 UTC, RomaricMourgues commented
It seems weblate is doing this itself: https://github.com/linagora/Twake/pull/1448/files
I prefer to reduce the number of changes we do to the language file to avoid merge issues with weblate if possible.

2021-08-23 07:26 UTC, RomaricMourgues commented
@BenoitTallandier it was a good idea, thanks for trying to fix this indent issue :p

2021-08-23 12:46 UTC, merged