#1808: bootstrap status work again
linagora/Twake pull request #1809
Opened 2021-12-08 11:28 UTC by tissarni

Users status is not  available anymore in Twake. The mission is to re-implement it to put it back in production

## Description

 - [ ] Create new route to update status
 - [ ] Create front component to change status
 - [ ] Add features to just have an emoji status
 - [ ] Keep same process and UI now in production (Emoji and text status)
 
## Related Issue

#1808

2021-12-13 15:00 UTC, stephanevieira75 requested changes

2021-12-13 15:00 UTC, stephanevieira75 commented on twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/SaveNewStatus.tsx
> +export default (props: PropsType): JSX.Element => {
`export default ({ level }: PropsType): JSX.Element => { ...`

2021-12-13 15:00 UTC, stephanevieira75 commented on twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/SaveNewStatus.tsx
> +import classNames from 'classnames';
This should be line 3

2021-12-13 15:00 UTC, stephanevieira75 commented on twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/SaveNewStatus.tsx
> +  level: any;
Can you try to find the level type please ?

2021-12-13 15:00 UTC, stephanevieira75 commented on twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/CurrentUser/SaveNewStatus.tsx
> +    document.addEventListener('keydown', listener);
I don't think you need this useEffect to add an event listener like this as you already use it directly line 48:

``` tsx
 <div
      onKeyDown={evt => {
        if (evt.key === 'Enter') save();
      }}
    >
....
```

2021-12-13 21:44 UTC, RomaricMourgues commented
@tissarni is it OK to merge ?

2021-12-13 21:56 UTC, RomaricMourgues approved these changes

2021-12-14 09:57 UTC, RomaricMourgues approved these changes

2021-12-14 09:58 UTC, merged