#1900 Workspace members invite fixes
linagora/Twake pull request #1911
Opened 2022-01-27 15:07 UTC by stephanevieira75

# #1744 & #1900 Workspace member can invite or delete pending-emails only

https://user-images.githubusercontent.com/36481167/151386558-2cc0a515-c367-41a3-aabe-568a99f6e55e.mp4

# #1901 Add a notice to warn users that the company has reached the maximum number of users it can invite

https://user-images.githubusercontent.com/36481167/152163765-12bd069f-b85c-4983-97e2-1e2dbd920e48.mp4

2022-01-31 10:10 UTC, RomaricMourgues commented
@BenoitTallandier could you confirm this new rules:
- Admins AND members can invite users to the workspace or get invitation link (before only admins)
- Admins AND members can remove pending invitations or re-generate invitation link (before only admins)
- Only Admins can remove members from the workspace
- Only Admins can set an other member as admin or not
- Guests cannot see or invite users to the workspace

2022-01-31 10:16 UTC, BenoitTallandier commented
Yes, I confirm these rules :)

2022-02-03 08:53 UTC, RomaricMourgues requested changes

2022-02-03 08:53 UTC, RomaricMourgues commented on twake/backend/node/src/services/user/web/types.ts
> +  COMPANY_LIMIT_NOT_REACHED = "company:limit_not_reached",
Alors j'ai réfléchis cette nuit on va faire un gros chercher remplacer:
COMPANY_LIMIT_NOT_REACHED -> COMPANY_INVITE_MEMBER
company:limit_not_reached -> company:invite_member

2022-02-03 08:53 UTC, RomaricMourgues commented on twake/backend/node/src/services/workspaces/web/routes.ts
> +      // TODO error auth msg
On peut enlever les TODOs ?

2022-02-03 08:53 UTC, RomaricMourgues commented on twake/backend/node/src/services/workspaces/web/routes.ts
> +      // TODO error auth msg
On peut enlever les TODOs ?

2022-02-03 09:45 UTC, stephanevieira75 commented on twake/backend/node/src/services/user/web/types.ts
> +  COMPANY_LIMIT_NOT_REACHED = "company:limit_not_reached",
Good :+1

2022-02-07 17:22 UTC, merged