#2217
linagora/Twake pull request #2228
Opened 2022-06-03 13:42 UTC by rezk2ll

## Description

- adds the link preview 

## Related Issue

https://github.com/linagora/Twake/issues/2217

## Motivation and Context

- display previews for links detected in messages.

## How Has This Been Tested?

- locally

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/6764881/171865977-4d9955cd-8f2a-423b-8c37-5b4400c3c79a.mp4

![image](https://user-images.githubusercontent.com/6764881/171865254-7f35f9e4-4c26-4d18-9a3a-845aad5f7da1.png)
![image](https://user-images.githubusercontent.com/6764881/171865305-22f0cfed-f5fc-41f5-b960-d9027fc87e73.png)
![image](https://user-images.githubusercontent.com/6764881/171865496-d69a8196-c72b-4c37-96fb-ad2797a90128.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added the Signed-off-by statement at the end of my commit message.

2022-06-03 14:10 UTC, RomaricMourgues commented
Nice, I'll have some design change proposals later, I already have this ones:
- Reduce size of favicon (they seems blurry, I think default size is 16px)
- Align title first line with the favicon itself
- Add the domain name (like youtube.com) just under the title
- Reduce the title size (I think the same size as the description is ok, bold should be enough to differentiate title and description)
- If not already done, of course make it clickable, on slack the title is in blue and is clikable if we want to follow they implmentaiton

2022-06-06 15:10 UTC, rezk2ll commented
updated:

https://user-images.githubusercontent.com/6764881/172189041-9afda088-0d7c-442e-937a-558357bdf1c4.mp4

![image](https://user-images.githubusercontent.com/6764881/172188856-703f40b7-95d1-480c-97b6-5a0546eafda0.png)
![image](https://user-images.githubusercontent.com/6764881/172189022-32a1cfbf-f072-4fd9-b9e1-1de818479b9c.png)

2022-06-07 09:17 UTC, RomaricMourgues commented
More change request:
- Let's put the domain next to the favicon instead of the title.
- Let's put the title aligned with the description
- Add border radius to the bottom on the link too

![172189022-32a1cfbf-f072-4fd9-b9e1-1de818479b9c](https://user-images.githubusercontent.com/14353924/172344066-af256448-2932-4641-956f-f46541b5bed5.png)

2022-06-07 11:29 UTC, RomaricMourgues requested changes

2022-06-07 11:29 UTC, RomaricMourgues commented on twake/frontend/src/app/views/applications/messages/message/parts/MessageContent.tsx
> +              )}
No that's wrong, a message can have both links and files actually

2022-06-07 12:57 UTC, merged